# templates/mock-crd.yaml
{{- if .Values.enableMockCRD }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: profiles.config.projectsveltos.io
spec:
  group: config.projectsveltos.io
  names:
    kind: Profile
    listKind: ProfileList
    plural: profiles
    singular: profile
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
{{- end }}